import type { Workflow } from '@/types';

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    _id: 'wf_001',
    userId: 'user_001',
    name: 'Fetch and Process User Data',
    description: 'Calls user API, validates response, transforms payload',
    isGeneratedByAI: false,
    nodes: [
      {
        id: 'node_0',
        type: 'start',
        label: 'Start',
        position: { x: -100, y: 200 },
        config: {},
      },
      {
        id: 'node_1',
        type: 'api_call',
        label: 'Fetch Users',
        position: { x: 150, y: 200 },
        config: {
          url: 'https://jsonplaceholder.typicode.com/users',
          method: 'GET',
          headers: { Accept: 'application/json' },
          timeout: 5000,
        },
      },
      {
        id: 'node_2',
        type: 'condition',
        label: 'Check Status',
        position: { x: 430, y: 200 },
        config: { expression: '{{node_1.status}} === 200' },
      },
      {
        id: 'node_3',
        type: 'transform',
        label: 'Extract Names',
        position: { x: 720, y: 100 },
        config: {
          transformCode: 'return input.data.map(u => ({ name: u.name, email: u.email }))',
          description: 'Extract name and email',
        },
      },
      {
        id: 'node_4',
        type: 'output',
        label: 'Log Error',
        position: { x: 720, y: 310 },
        config: {
          logLevel: 'error',
          message: 'API failed: status {{node_1.status}}',
        },
      },
      {
        id: 'node_5',
        type: 'end',
        label: 'End',
        position: { x: 1000, y: 200 },
        config: {},
      },
    ],
    edges: [
      { id: 'edge_0', source: 'node_0', target: 'node_1' },
      { id: 'edge_1', source: 'node_1', target: 'node_2' },
      { id: 'edge_2', source: 'node_2', target: 'node_3', sourceHandle: 'condition_true', conditionBranch: 'true', label: 'Yes' },
      { id: 'edge_3', source: 'node_2', target: 'node_4', sourceHandle: 'condition_false', conditionBranch: 'false', label: 'No' },
      { id: 'edge_4', source: 'node_3', target: 'node_5' },
      { id: 'edge_5', source: 'node_4', target: 'node_5' },
    ],
    createdAt: '2025-06-01T10:00:00.000Z',
    updatedAt: '2025-06-03T14:30:00.000Z',
  },
  {
    _id: 'wf_002',
    userId: 'user_001',
    name: 'Delayed Notification Pipeline',
    description: 'Fetch data, wait, then send notification',
    isGeneratedByAI: true,
    nodes: [
      {
        id: 'node_0',
        type: 'start',
        label: 'Start',
        position: { x: -100, y: 200 },
        config: {},
      },
      {
        id: 'node_1',
        type: 'api_call',
        label: 'Fetch Alerts',
        position: { x: 150, y: 200 },
        config: {
          url: 'https://jsonplaceholder.typicode.com/posts',
          method: 'GET',
          headers: {},
          timeout: 3000,
        },
      },
      {
        id: 'node_2',
        type: 'delay',
        label: 'Wait 5s',
        position: { x: 430, y: 200 },
        config: { delayMs: 5000 },
      },
      {
        id: 'node_3',
        type: 'output',
        label: 'Send Alert',
        position: { x: 710, y: 200 },
        config: {
          logLevel: 'info',
          message: 'Alert dispatched: {{node_1.data}}',
        },
      },
      {
        id: 'node_4',
        type: 'end',
        label: 'End',
        position: { x: 960, y: 200 },
        config: {},
      },
    ],
    edges: [
      { id: 'edge_0', source: 'node_0', target: 'node_1' },
      { id: 'edge_1', source: 'node_1', target: 'node_2' },
      { id: 'edge_2', source: 'node_2', target: 'node_3' },
      { id: 'edge_3', source: 'node_3', target: 'node_4' },
    ],
    createdAt: '2025-06-02T08:00:00.000Z',
    updatedAt: '2025-06-02T08:00:00.000Z',
  },
  {
    _id: 'wf_003',
    userId: 'user_001',
    name: 'Data Transformation Chain',
    description: 'Multi-step data processing pipeline',
    isGeneratedByAI: false,
    nodes: [
      {
        id: 'node_0',
        type: 'start',
        label: 'Start',
        position: { x: -100, y: 200 },
        config: {},
      },
      {
        id: 'node_1',
        type: 'api_call',
        label: 'Load Raw Data',
        position: { x: 150, y: 200 },
        config: { url: 'https://jsonplaceholder.typicode.com/todos', method: 'GET', headers: {} },
      },
      {
        id: 'node_2',
        type: 'transform',
        label: 'Normalize Fields',
        position: { x: 430, y: 200 },
        config: { transformCode: 'return input.data.map(normalize)', description: 'Standardize field names' },
      },
      {
        id: 'node_3',
        type: 'transform',
        label: 'Aggregate Results',
        position: { x: 710, y: 200 },
        config: { transformCode: 'return { total: input.length, items: input }' },
      },
      {
        id: 'node_4',
        type: 'output',
        label: 'Export',
        position: { x: 990, y: 200 },
        config: { logLevel: 'info', message: 'Processed {{node_3.total}} records' },
      },
      {
        id: 'node_5',
        type: 'end',
        label: 'End',
        position: { x: 1240, y: 200 },
        config: {},
      },
    ],
    edges: [
      { id: 'edge_0', source: 'node_0', target: 'node_1' },
      { id: 'edge_1', source: 'node_1', target: 'node_2' },
      { id: 'edge_2', source: 'node_2', target: 'node_3' },
      { id: 'edge_3', source: 'node_3', target: 'node_4' },
      { id: 'edge_4', source: 'node_4', target: 'node_5' },
    ],
    createdAt: '2025-05-28T16:45:00.000Z',
    updatedAt: '2025-06-01T09:15:00.000Z',
  },
];
